language: node_js
node_js:
  - lts/*
sudo: false
env:
  global:
  - secure: We1Gbm4rAT9LrVz3hNoVQtUajjaDxEsLjCFFXvXVr90bMi4oeYwRy0nECJieI+ezsjgi4ymZABev5vhIyXx0yOEEGdTOJUdOXf4fjAQx0z5ps0BUx9R4F7V9WPfu1ClGp92bdmeGPvvbDgrls9YB8K4dn1ulB4DuPaJHrisn/Tc=
  - secure: gnyyKCi3ZR4ImCvcOeFUED0Ks0PcdnQUL43SBqWU6Af23N/krKDPPmrwwP2n+ynywjysMfOIrjWUJZIcP8Yr6gEQ1TxH/kBizdoOMEWG844MhCsluuZ1wlHYe9+Mmb1UZ0ccWEjhN3DSagGbXA41CcIotxEsw9pwOnv5Aa7cXpk=
